### ISSUE TITLE
Alternative for spar positioning definition at rib

### ISSUE THREAD

**Issue by sdeinert** [DLR-LY/CPACS#544]
In models that have spars with kinks these kinks are often reinforced with a rib due to constructive reasons. This means the kink positions of the spars and the location of the rib need to coincide exactly.

With the current definition of the spar positions this is only theoretically possible. One can adjust the eta position long enough until kink and rib location coincide. However, this can only be guaranteed for the current geometry, whenever other parameters (e.g. sweep, span, twist) are changed the positions might not lie on the rib anymore.

Therefore, I propose the following extension to the existing CPACS definition of the sparPosition as an alternative to the eta/xsi definition:
```xml
<sparPosition uID="WingSpar1Positioning1">
  <ribNumber>2</ribNumber>
  <ribDefinitionUID>theRib</ribDefinitionUID>
  <xsi>0.2</xsi>
</sparPosition>
```
This follows the same definition logic as for example the inner border definition of the wing cell.
Here, the xsi value would then be assumed on the rib line from rib start to rib end.

Do you think this would be feasible?
It would be merely an extension of the existing scheme without breaking backwards compatibility reusing a practice that is already applied elsewhere.

**Comment by codingpoets** [comment]
Although it is the other way around in #533 I think this problem is solved with the solution suggested in #546. Is there a reason why we need it spar positioning via rib when we have rib positioning via spars?

**Comment by sdeinert** [comment]
Unfortunately #546 does not solve the problem. This addition only allows placing a ribDefinition relative to one spar. However, it is often required to have a kink in a number of spars at a specific rib position. With the definition in #546 it would only be possible to define such a kink for one spar since the rib reference can only reference one spar.

Therefore, in my opinion both definition methods are required. #546 for example to place a rib at the exact end position of a spar that ends somewhere within a wing. The functionality here would be to place several spars at one specific rib. So in summary #546 allows a placement of n ribs relative to 1 spar. The proposal here allows a placement of n spars relative to 1 rib.

**Comment by codingpoets** [comment]
I am not sure I fully get your doubts. The proposal in #546 allows you to select a specific spar point at which the rib location will start and a different spar point for the end. I guess in order to solve the problem that you mention you would have to define multiple ribsDefinitions. Or did I miss your point?
if you want to 

> place several spars at one specific rib.

you can have the sparSegments share a singel sparPoint and have that connect to the rib.

In addition to that I just realized that we probably want to use the positioning via explicit spar point also for the wingRibExplicitPositioningType.

**Comment by codingpoets** [comment]
Also for a straight rib there can only be two spar points through which the rib is defined. If you have more than two, you need to make sure that the fall on a single line. Otherwise, as far as I understand, you will just have to define two separate explicit ribs.

**Comment by sdeinert** [comment]
As shown here, there are two spars (red) that shall have a kink at a specific rib (green).
![wing_spars_at_rib](https://user-images.githubusercontent.com/15669066/41418671-7ec5b4c6-6ff0-11e8-8471-04084d667276.png)
With the definition in #546 it would be possible to create this rib at one of the spars but not at both, since it can only reference one spar. Therefore, the second spar would have to be manually adjusted using an eta/xsi sparPosition to somewhat meet the rib with its kink.

With the proposition here it would be possible to define a number of sparPositions at this one rib with different sparSegments using those sparPositions. This way it would always be guaranteed that the spar kinks exactly meet the position of the rib.

**Comment by codingpoets** [comment]
Isn't it possible to define the rib that you mention by the following structure:

```
<sparPositionStartUID>SparPoint1</sparPositionStartUID>
<sparPositionEndUID>SparPoint2</sparPositionEndUID>
<ribStart>leadingEdge</ribStart>
<ribEnd>trailingEdge</ribEnd>
<numberOfRibs>1</numberOfRibs>
```

What do you think?

**Comment by sdeinert** [comment]
I am not sure if this definition is correct, as start and end usually is used for inboard and outboard limits of the ribset. Here, you are using it as leading edge and trailing edge end. I don't think this definition was intended this way.

Additionally, this would only support two spars. In our cases we often have up to 10 or more spars

**Comment by codingpoets** [comment]
Okay, I think I get the issue now. You need to extend or cut the spars at a defined rib since you cannot ensure the spar points to be in a straight line coinciding with the rib. Therefore the reverse is also needed. 
Only problem I see is that I have no idea how to restrict the definition such that a rib which is using a sparPoint for its own placement is not at the same time used by in the definition of the spar point. THat would lead to an undefined structure. But it should be common sense to not do that. Also since rib and spar are linked directly this should be easy to discover, don't you think?

**Comment by sdeinert** [comment]
Yes you are right. This cannot be prevented by the schema. A logic check needs to be done by the software using this data set.

**Comment by codingpoets** [comment]
Ok, here is a suggestion for a solution.

```
<sparPositions>
  <sparPositionRib> <!-- [0, *]; new definition of wingRibPointType-->
    <ribDefinitionUID /> <!-- [1, 1] -->
    <ribNumber /> <!-- optional [0, 1], defaults to 1; ignored in case ribDefinitionUID points to an explicit rib definition -->
    <xsi /> <!-- [1, 1] -->
  </sparPositionRib>
  <sparPositionEtaXsi> <!-- [0, *]; etaXsiPointType -->
    <eta />
    <xsi />
    <referenceUID />
  </sparPositionEtaXsi>
</sparPositions>
```
As you can see I would suggest to 
1. add the spar position via rib as a separate nod ein the sparPositions list and
2. rename the sparPosition to sparPositionEtaXsi and
3. change the definition of 2. to the etaXsiPointType as defined in #546 

Any objections or remarks on this?
